# Generated by Django 4.2 on 2023-05-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_saved_description_alter_saved_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='description',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='name',
        ),
    ]
