# Generated by Django 4.2 on 2023-05-09 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_saved_description_remove_saved_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='recipe',
        ),
        migrations.AddField(
            model_name='saved',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('measurement', models.CharField(choices=[('oz', 'ounce'), ('g', 'gram'), ('lb', 'pound'), ('kg', 'kilogram'), ('pinch', 'pinch'), ('l', 'liter'), ('gal', 'Gallon'), ('pint', 'Pint'), ('qt', 'Quart'), ('ml', 'Mililiter'), ('cup', 'Cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon')], default='oz', max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
    ]
