# Generated by Django 4.2 on 2023-05-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(max_length=6),
        ),
    ]
