# Generated by Django 4.2 on 2023-05-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_savedrecipes_delete_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipes',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
