# Generated by Django 4.2 on 2023-05-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_savedrecipes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipes',
            name='name',
            field=models.CharField(),
        ),
    ]
