# Generated by Django 4.2 on 2023-05-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_savedrecipes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='savedrecipes',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
            preserve_default=False,
        ),
    ]
