# Generated by Django 4.2 on 2023-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_savedrecipes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipes',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.RemoveField(
            model_name='savedrecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='savedrecipes',
            name='recipes',
            field=models.ManyToManyField(to='main_app.recipe'),
        ),
    ]
