# Generated by Django 4.2 on 2023-05-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_savedrecipes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('measurement', models.CharField(max_length=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='main_app.RecipeIngredients', to='main_app.ingredients'),
        ),
    ]
