# Generated by Django 4.2 on 2023-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_ingredients_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
