# Generated by Django 4.2 on 2023-05-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_ingredients_amount_ingredients_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.FloatField(blank=True, default=''),
        ),
    ]
