# Generated by Django 4.2 on 2023-05-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_ingredients_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='measurement',
            field=models.CharField(max_length=6),
        ),
    ]
