# Generated by Django 4.2 on 2023-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_ingredients_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(choices=[('oz', 'ounce'), ('g', 'gram'), ('lb', 'pound'), ('kg', 'kilogram'), ('pinch', 'pinch'), ('l', 'liter'), ('gal', 'Gallon'), ('pint', 'Pint'), ('qt', 'Quart'), ('ml', 'Mililiter'), ('cup', 'Cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('pieces', 'pieces')], default='oz', max_length=6),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='measurement',
            field=models.CharField(choices=[('oz', 'ounce'), ('g', 'gram'), ('lb', 'pound'), ('kg', 'kilogram'), ('pinch', 'pinch'), ('l', 'liter'), ('gal', 'Gallon'), ('pint', 'Pint'), ('qt', 'Quart'), ('ml', 'Mililiter'), ('cup', 'Cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('pieces', 'pieces')], default='oz', max_length=6),
        ),
    ]
