# Generated by Django 4.2 on 2023-05-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={},
        ),
    ]
