# Generated by Django 4.2 on 2023-05-12 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_alter_ingredients_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipes',
            name='recipes',
        ),
        migrations.AddField(
            model_name='savedrecipes',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedrecipes',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedrecipes',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
