# Generated by Django 4.2 on 2023-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_remove_savedrecipes_recipes_savedrecipes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipes',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedrecipes',
            name='ingredients',
            field=models.TextField(max_length=2000),
        ),
    ]
